### ISSUE TITLE
getting an API Key documentation

### ISSUE THREAD

**Issue by vsudilov** [adsabs/help#5]
_From @kelle on June 16, 2015 14:49_

The documentation for getting an API key is presently blank
http://adsabs.github.io/help/api/api-key/
Consider just pasting this in:
If you would like to develop widgets or applications to interface with ADS services, you can generate an API Key by [creating an account] (https://www.google.com/url?q=https%3A%2F%2Fui.adsabs.harvard.edu%2F%23user%2Faccount%2Fregister)  and navigating to the API Token section in Settings. We are looking forward to seeing what the community builds with these services and encourage folks to requests API Keys several days in advance of any hack days.

_Copied from original issue: adsabs/bumblebee#421_

**Comment by jonnybazookatone** [comment]
I would have thought this can be closed as the pages now point to the new API docs on the repo?

**Comment by kelle** [comment]
could you include a link to the page? The one i have doesn't work.

**Comment by jonnybazookatone** [comment]
http://adsabs.github.io/help/api/

**Comment by jonnybazookatone** [comment]
@kelle: any other comments than #10? Otherwise this ticket can be closed.

**Comment by kelle** [comment]
close it! :)

**Comment by jonnybazookatone** [comment]
Thx.
