### ISSUE TITLE
Add "Edit this page on GitHub" link to the Help Pages

### ISSUE THREAD

**Issue by vsudilov** [adsabs/help#7]
_From @kelle on June 15, 2015 20:5_

Encourage/enable very interested users to help out with the Help pages. Check out the astropy docs (http://docs.astropy.org/en/latest/index.html), scroll to the bottom and notice they have an "Edit this page on GitHub" link. I may not contribute much code to astropy, but I have submitted several pull requests to the documentation!

_Copied from original issue: adsabs/bumblebee#419_

**Comment by aholachek** [comment]
jonny added this
